name: Convert docx to markdown

on:
  push:
    paths:
      - '**.docx'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pandoc
        run: |
          sudo apt update
          sudo apt install pandoc

      - name: Convert docx to markdown
        run: |
          for file in $(find . -name "*.docx"); do
            pandoc -f docx -t markdown "$file" -o "${file%.docx}.md"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
    
