name: Convert docx to markdown

on:
  push:
    paths:
      - '**/*.docx'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pandoc
        run: |
          sudo apt update
          sudo apt install pandoc

      - name: Convert docx to markdown
        run: |
          for file in $(find . -name "*.docx"); do
            pandoc -f docx -t markdown "$file" -o "${file%.docx}.md"
          done

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Convert DOCX to Markdown" || echo "No changes to commit"
          git push
    
